// Adressen voor wijk 1 
const wijk1Data = [
    { "name": "Fam. Heger", "address": "Burg. Heijsingel 36", "comment": "2x" },
    { "name": "Fam. Visser", "address": "Leidjeskamp 24", "comment": "" },
    { "name": "Fam. van Veldhuizen", "address": "t'Boschstuk 20", "comment": "" },
    { "name": "Fam. Blankenspoor", "address": "Ruitenbeekskamp 11", "comment": "" },
    { "name": "Fam. Velthuizen", "address": "Voermanskamp 2", "comment": "Brievenbus aan de voorposten" },
    { "name": "Dhr. van Veldhuizen", "address": "Lijsterbeslaan 22", "comment": "" },
    { "name": "Mw. van Oossanen", "address": "Heijhorst 5", "comment": "" },
    { "name": "Fam. Wols", "address": "Hovenierslaan 40", "comment": "" },
    { "name": "Fam. van de Hoek", "address": "Hovenierslaan 22", "comment": "" },
    { "name": "Fam. Berkhof", "address": "Hovenierslaan 12", "comment": "" },
    { "name": "Mw. van de Vliert", "address": "Grebbelaan 2", "comment": "" },
    { "name": "Fam. van de Zandschulph", "address": "Valleilaan 27", "comment": "" },
    { "name": "Fam. Overeem", "address": "Grebbelaan 16", "comment": "" },
    { "name": "Fam. Westeneng", "address": "Het Pella 1", "comment": "" },
    { "name": "Fam. Brand", "address": "Burg. Colijn de Raadsingel 12", "comment": "" },
    { "name": "Dhr. Hardeman", "address": "Vierzinnen 52", "comment": "" },
    { "name": "Fam. Heijkamp", "address": "Vierzinnen 18", "comment": "" },
    { "name": "Mw. van Setten", "address": "Lindenlaan 54", "comment": "" },
    { "name": "Mw. Kieft", "address": "Lindenlaan 32", "comment": "" },
    { "name": "Mw. ten Broek", "address": "Wilgenhof 29", "comment": "" },
    { "name": "Fam. Gardenier", "address": "Wilgenhof 33", "comment": "" },
    { "name": "Fam. Geurtsen", "address": "Willaerlaan 50", "comment": "" },
    { "name": "Dhr. Versteeg", "address": "Pr Irenelaan 32", "comment": "" },
    { "name": "Fam. Meerkerk", "address": "Pr Marijkelaan 44", "comment": "" },
    { "name": "Fam. Uitbeijersen", "address": "Ruijsdaellaan 12", "comment": "" },
    { "name": "Dhr. van de Kamp", "address": "Ruijsdaellaan 15", "comment": "" },
    { "name": "Fam. Florijn", "address": "Rembrandtlaan 50", "comment": "" },
    { "name": "Fam. Berkhof", "address": "Eikenlaan 77", "comment": "" },
    { "name": "Fam. van Rumpt", "address": "Egelpad 5", "comment": "" },
    { "name": "Fam. den Braber", "address": "Eikenlaan 129", "comment": "" },
    { "name": "Fam. Leijen", "address": "Rembrandtlaan 84", "comment": "" },
    { "name": "Fam. Koppe", "address": "Paulus Potterlaan 19", "comment": "" },
    { "name": "Fam. v.d. Brink", "address": "Paulus Potterlaan 21", "comment": "" },
    { "name": "Fam. de Kruijf", "address": "Burg. H.v. Konijnenburglaan 34", "comment": "" },
    { "name": "Fam. Gardenier", "address": "Burg. H.v. Konijnenburglaan 30", "comment": "" },
    { "name": "Dhr. Kampert", "address": "Burg. H.v. Konijnenburglaan 13", "comment": "" },
    { "name": "Fam. v.d. Wetering", "address": "Frans Halslaan 20", "comment": "" },
    { "name": "Fam. Schouten", "address": "Frans Halslaan 34", "comment": "" },
    { "name": "Fam. de Ruiter", "address": "Burg. H v. Konijnenburglaan 14", "comment": "" }
];

// Adressen voor wijk 2
const wijk2Data = [
    { "name": "Mw. van de Broek", "address": "Vermeerlaan 1", "comment": "" },
    { "name": "Wilmar Hardeman", "address": "Glashorst 46", "comment": "" },
    { "name": "Fam. Wisse", "address": "Glashorst 68", "comment": "" },
    { "name": "Fam. de Jager", "address": "Glashorst 70", "comment": "" },
    { "name": "Fam. Velthuizen", "address": "Pluimenweg 17", "comment": "" },
    { "name": "Fam. van Ginkel", "address": "Industrielaan 10", "comment": "" },
    { "name": "Fam. van de Kamp", "address": "Prinsenlaan 42", "comment": "" },
    { "name": "Fam. den Hartog", "address": "Prinsenlaan 35", "comment": "" },
    { "name": "Mw. Boer", "address": "Stationsweg 334", "comment": "" },
    { "name": "Fam. Haanschoten", "address": "Stationsweg 338", "comment": "" },
    { "name": "Fam. van Dijkhuizen", "address": "Industrielaan 4", "comment": "" },
    { "name": "Fam. van den Bosch", "address": "Burg. Röell-laan 9", "comment": "" },
    { "name": "Mw. Mulder", "address": "Holevoetlaan 45", "comment": "" },
    { "name": "Fam. Westeneng", "address": "Het Pella 1", "comment": "" },
    { "name": "Fam. Brand", "address": "Burg. Colijn de Raadsingel 12", "comment": "" },
    { "name": "Dhr. Hardeman", "address": "Vierzinnen 52", "comment": "" },
    { "name": "Fam. Heijkamp", "address": "Vierzinnen 18", "comment": "" },
    { "name": "Mw. van Setten", "address": "Lindenlaan 54", "comment": "" },
    { "name": "Mw. Kieft", "address": "Lindenlaan 32", "comment": "" },
    { "name": "Mw. ten Broek", "address": "Wilgenhof 29", "comment": "" },
    { "name": "Fam. Gardenier", "address": "Wilgenhof 33", "comment": "" },
    { "name": "Fam. Geurtsen", "address": "Willaerlaan 50", "comment": "" },
    { "name": "Dhr. Versteeg", "address": "Pr Irenelaan 32", "comment": "" },
    { "name": "Fam. Meerkerk", "address": "Pr Marijkelaan 44", "comment": "" },
    { "name": "Fam. Uitbeijersen", "address": "Ruijsdaellaan 12", "comment": "" },
    { "name": "Dhr. van de Kamp", "address": "Ruijsdaellaan 15", "comment": "" },
    { "name": "Fam. Florijn", "address": "Rembrandtlaan 50", "comment": "" },
    { "name": "Fam. Berkhof", "address": "Eikenlaan 77", "comment": "" },
    { "name": "Fam. van Rumpt", "address": "Egelpad 5", "comment": "" },
    { "name": "Fam. den Braber", "address": "Eikenlaan 129", "comment": "" },
    { "name": "Fam. Leijen", "address": "Rembrandtlaan 84", "comment": "" },
    { "name": "Fam. Koppe", "address": "Paulus Potterlaan 19", "comment": "" },
    { "name": "Fam. v.d. Brink", "address": "Paulus Potterlaan 21", "comment": "" },
    { "name": "Fam. de Kruijf", "address": "Burg. H.v. Konijnenburglaan 34", "comment": "" },
    { "name": "Fam. Gardenier", "address": "Burg. H.v. Konijnenburglaan 30", "comment": "" },
    { "name": "Dhr. Kampert", "address": "Burg. H.v. Konijnenburglaan 13", "comment": "" },
    { "name": "Fam. v.d. Wetering", "address": "Frans Halslaan 20", "comment": "" },
    { "name": "Fam. Schouten", "address": "Frans Halslaan 34", "comment": "" },
    { "name": "Fam. de Ruiter", "address": "Burg. H v. Konijnenburglaan 14", "comment": "" }
];
